### ISSUE TITLE
Error creating entity

### ISSUE THREAD

**Issue by bbr111** [89jd/hass-roborock#14]
Hi,

i used an ssl inspection proxy to extract duid and localkey from roborock app.

setting up integration using this parameters:
Name = Roborock S7
duid = Device ID
localkey = API Token
ip = my.local.ip

No entity is shown up:

following error in homeassistant.log:

2021-03-29 23:12:23 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up roborock platform for vacuum
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/homeassistant/.homeassistant/custom_components/roborock/vacuum.py", line 149, in async_setup_entry
    vacuum = Roborock(ip=host, device_id=device_id, token=token, js_dir=js_dir)
  File "/srv/homeassistant/lib/python3.8/site-packages/pyroborock/__init__.py", line 150, in __init__
    super().__init__(ip, token, debug=debug)
  File "/srv/homeassistant/lib/python3.8/site-packages/miio/vacuum.py", line 91, in __init__
    super().__init__(ip, token, start_id, debug)
  File "/srv/homeassistant/lib/python3.8/site-packages/miio/device.py", line 122, in __init__
    self._protocol = MiIOProtocol(ip, token, start_id, debug, lazy_discover)
  File "/srv/homeassistant/lib/python3.8/site-packages/miio/miioprotocol.py", line 42, in __init__
    self.token = bytes.fromhex(token)
ValueError: non-hexadecimal number found in fromhex() arg at position 1

**Comment by Xyaren** [comment]
Same here, any news ?

**Comment by alvesvaren** [comment]
same for me (S6 MaxV)
