### ISSUE TITLE
Entity does not show

### ISSUE THREAD

**Issue by Zeppen** [89jd/hass-roborock#8]
Im a bit confused.. 
Did ok to extract the token and so on but after installation the roborock (s6 maxv) doesn't show up as an entity as described. 
Whats wrong? 
![Screenshot_20210209-003312](https://user-images.githubusercontent.com/1380001/107294814-7366dd00-6a6e-11eb-8683-d8a264cdfbf2.jpg)

**Comment by Jelke87** [comment]
Same here no  entity show up.
```
Logger: homeassistant.components.vacuum
Source: custom_components/roborock/vacuum.py:146 
Integration: Stofzuigen (documentation, issues) 
First occurred: 14 maart 2021 14:17:08 (1 occurrences) 
Last logged: 14 maart 2021 14:17:08

Error while setting up roborock platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/vacuum.py", line 146, in async_setup_entry
    tuya_init(js_dir)
  File "/usr/local/lib/python3.8/site-packages/tuyapipc/__init__.py", line 106, in init
    Popen(['npm', 'install', 'tuyapi-ipc'], \
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm
```

**Comment by 89jd** [comment]
NPM needs to be installed to use.

See this forum here, lots of details on how to setup on docker, standalone etc. ->https://community.home-assistant.io/t/custom-component-roborock-communication/229032/120
